Version bump
imagekit-developer/imagekit-angular pull request #66
Opened 2023-08-09 09:47 UTC by Anubhavjain786

2023-08-25 05:34 UTC, imagekitio requested changes

2023-08-25 05:34 UTC, imagekitio commented on sdk/tests/sdk-tests/ik-image.component.spec.ts
> +      // authenticationEndpoint: "http://example.com/auth"
Instead of commenting please remove from all places.

2023-08-25 05:34 UTC, imagekitio commented on sdk/tests/sdk-tests/ik-upload.component.spec.ts
> +// import { ComponentFixture, TestBed } from '@angular/core/testing';
Why have we commented the whole test suite for upload?

2023-08-25 05:34 UTC, imagekitio commented on sdk/tests/test-apps/sample-server/package-lock.json
> +    "node_modules/accepts": {
Why huge changes in lock file?

2023-08-25 05:34 UTC, imagekitio commented on README.md
> +## Changelog - SDK Version 2.0.0
The current version is 2.0.1. So this `2.0.0` is incorrect. `package.json` has correct version.

2023-08-28 09:08 UTC, NikhilSejwal7 commented on sdk/tests/sdk-tests/ik-image.component.spec.ts
> +      // authenticationEndpoint: "http://example.com/auth"
Done

2023-08-28 09:09 UTC, NikhilSejwal7 commented on README.md
> +## Changelog - SDK Version 2.0.0
Fixed

2023-08-29 06:43 UTC, NikhilSejwal7 commented on sdk/tests/test-apps/sample-server/package-lock.json
> +    "node_modules/accepts": {
Fixed

2023-09-12 04:44 UTC, NikhilSejwal7 commented on sdk/tests/sdk-tests/ik-upload.component.spec.ts
> +// import { ComponentFixture, TestBed } from '@angular/core/testing';
Uncommented and fixed test cases that were failing

2023-12-04 09:27 UTC, closed without merging